elindow/APW1

html/golanka_page.html, scripts/golanka.js
a bouncing ball  using a .js file separate from the html file
=> added javascript

index.html, styles/style.css
=> Changed style sheet and added alert!!!

html/jakehtml.html
=> I made a web page and put an image and a button on it

html/jakehtml.html
=> changed button

html/jakehtml.html, scripts/freeman.js
=> js page added

html/FleesPage.html
Added the summary of my project to my project page
=> my summary for my project

html/golanka_page.html
For showing how to make a pull request.
=> added one line

html/Michael2.html, html/This is a test-michael.html, html/michael.html, scripts/michael.js, scripts/michael2.js, styles/michael.css, styles/michael2.css
=> Updated Files

index.html, scripts/freeman2.js, scripts/main.js
It needs work still but I think Ozan is going to fix the css and background formatting
=> some index changes

JacobWTetris/Jacobweingard.css, JacobWTetris/Jacobweingard.js, JacobWTetris/jacobweingard.html
Jacob Weingard's HTML page. Once I learn more about the structure of the repository I will be able to put the files in the places, separate, instead of together in the obtrusive file.
=> added jacob W's page, and the js and css files required to run Tetris

html/silverstein.css, html/silverstein.html
=> Linked the button so it does something

html/Robert.html
A changelog is visible on the new link
=> updated links

html/HaydenProjectpage.html
Added progress with adding colors to lights
=> Added project update 

html/McNuttSoFar.html
My Weekly update, Submitted 1/13/2021
=> McNuttSoFar

html/McNuttSoFar.html
=> McNuttSoFar.html

html/Melwani2.html
=> epic progress page update

html/gina_index.html, html/gina_mywork.html
=> Added final journals

html/will.html
I wanted to add my project ideas and to practice this process again of submitting my changes.
=> I added some details about a project I'd like to do onto my website.

html/kyle.html
=> added stuff, including a glitch savestate for pokemon red

Students/KyleNolan/html/kylenolanprojs.html
=> more stuff done
